name: Build Image and Push to Github Package
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: react-router/react-router
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
